version: '3.9'

services:
  database:
    container_name: todorush_database
    image: postgres:15.3
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - ./database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=todorush_database

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend.dev
    container_name: todorush_backend
    depends_on:
      - database
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/app

  telegram_bot:
    build:
      context: .
      dockerfile: ./Dockerfile.telegram_bot.dev
    container_name: todorush_telegram_bot
    depends_on:
      - database
    restart: on-failure
    volumes:
      - .:/app

volumes:
  database_data:
