version: '3.9'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: ./Dockerfile.telegram_bot.prod
    container_name: todorush_telegram_bot
    restart: on-failure
    volumes:
      - .:/app

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend.prod
    container_name: todorush_backend
    ports:
      - 8000:8000
    restart: on-failure
    volumes:
      - .:/app
