FROM python:3.12.0

WORKDIR /app
COPY ./requirements.txt ./requirements.txt

RUN pip install -r ./requirements.txt

CMD python3 ./edit_alembic_config.py && \
	alembic upgrade head && \
	python3 main.py
