"""Increase verification code length

Revision ID: d2c5db0d588e
Revises: 26daf61761e9
Create Date: 2023-11-24 17:29:24.915773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c5db0d588e'
down_revision: Union[str, None] = '26daf61761e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_code', 'value',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_code', 'value',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
